{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wellq.fullname" . }}-web
  labels:
    {{- include "wellq.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.web.minAvailable }}
  selector:
    matchLabels:
      {{- include "wellq.selectorLabels" . | nindent 6 }}
      component: web
{{- end }}

