{{- if .Values.secrets.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wellq.fullname" . }}-secrets
  labels:
    {{- include "wellq.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  {{- if .Values.database.external.enabled }}
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.redisExternal.enabled }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}

